# -*- coding: utf-8 -*-
"""resume_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165RwneAgVaGFozs9xNL_R-jNpE0YjpVd
"""

import pandas as pd

df= pd.read_csv('resume_dataset_clean.csv')

df.head()

df.tail()

df.columns

df.info()

df.shape

df.isnull().sum()

"""Cleaning resume text = removing noise and keeping only useful words (skills, job info, experience) so AI can learn patterns properly."""

import re

def clean_text(text):
    text = re.sub(r'http\S+', ' ', text)      # remove links
    text = re.sub(r'[^a-zA-Z]', ' ', text)    # keep only letters
    text = text.lower()                       # convert to lowercase
    text = re.sub(r'\s+', ' ', text)          # remove extra spaces
    return text

df['clean_resume'] = df['Resume'].apply(clean_text)

df[['Resume', 'clean_resume']].head()

X = df['clean_resume'] #INPUT (what model reads)  LEARNS FROM X (INFORMATION)
y = df['Category']   #OUTPUT (what model predicts)  PREDICTS FROM Y (ANSWER)

"""text into numbers

import tf idf
"""

from sklearn.feature_extraction.text import TfidfVectorizer

#Create the vectorizer
tfidf = TfidfVectorizer()

#Fit + Transform your data
#fit() → learns all words (vocabulary)  transform() → converts resumes into numbers
X=tfidf.fit_transform(df['clean_resume'])

print(X.shape)   #resumes and unique words(features)

"""**Train-Test Split → Model Training**"""

from sklearn.model_selection import train_test_split

#Split (THIS CREATES X_train)
X_train, X_test, y_train, y_test = train_test_split(
    df['clean_resume'], df['Category'],
    test_size=0.2, random_state=42)

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize and apply TfidfVectorizer to convert text into numerical features
tfidf = TfidfVectorizer()
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

model = MultinomialNB()
model.fit(X_train, y_train)

#make prediction
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

"""### Investigate Categories for potential issues

To understand why the accuracy is 1.0, let's examine the distribution of the categories in the `Category` column. This can reveal if there's a significant class imbalance or if the dataset contains only one category, which would trivially lead to perfect accuracy.
"""

# Check the unique categories and their counts
print(df['Category'].value_counts())

# Also check the number of unique categories
print(f"Number of unique categories: {df['Category'].nunique()}")

"""### Loading a more diverse dataset

Let's assume you've found a new CSV file named `diverse_resume_dataset.csv` with multiple categories. You can load it and inspect its contents:
"""

# Load the new diverse dataset
try:
    df_diverse = pd.read_csv('diverse_resume_dataset.csv')
    print("Diverse dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'diverse_resume_dataset.csv' not found. Please upload it or specify the correct path.")
    print("For demonstration, creating a dummy diverse dataset with multiple categories.")
    data = {
        'Resume': [
            'Python Developer resume with Django and Flask skills',
            'Data Scientist resume with Python R and Machine Learning',
            'Web Developer resume with HTML CSS JavaScript React',
            'Python Developer focused on backend APIs and databases',
            'Data Scientist specializing in statistical modeling and data visualization',
            'Web Developer experienced in frontend development and UI/UX'
        ],
        'Category': [
            'Python_Developer',
            'Data_Scientist',
            'Web_Developer',
            'Python_Developer',
            'Data_Scientist',
            'Web_Developer'
        ]
    }
    df_diverse = pd.DataFrame(data)

# Display the first few rows of the new dataframe
display(df_diverse.head())

"""Now, let's examine the categories in this new dataset to ensure it has the diversity needed for classification."""

# Check the unique categories and their counts in the diverse dataset
print(df_diverse['Category'].value_counts())

# Also check the number of unique categories
print(f"Number of unique categories: {df_diverse['Category'].nunique()}")

"""### Cleaning and Preparing the Diverse Dataset

First, we need to clean the 'Resume' text in our `df_diverse` dataframe using the same `clean_text` function defined earlier. This will create a 'clean_resume' column suitable for vectorization.
"""

# Apply the clean_text function to the new diverse dataframe
df_diverse['clean_resume'] = df_diverse['Resume'].apply(clean_text)

# Display the first few rows to verify cleaning
print(df_diverse[['Resume', 'clean_resume']].head())

"""Next, we'll define our input features `X_diverse` (the cleaned resumes) and our target variable `y_diverse` (the categories) from the `df_diverse` dataframe."""

# Define input (X) and output (y) for the diverse dataset
X_diverse = df_diverse['clean_resume']
y_diverse = df_diverse['Category']

"""Now, we will split the diverse dataset into training and testing sets. It's crucial to use `stratify=y_diverse` to ensure that each category is represented proportionally in both the training and testing sets, which is especially important for multi-class classification with potentially imbalanced classes."""

from sklearn.model_selection import train_test_split

# Split the diverse data into training and testing sets
X_train_diverse, X_test_diverse, y_train_diverse, y_test_diverse = train_test_split(
    X_diverse, y_diverse,
    test_size=0.5, random_state=42, stratify=y_diverse # Stratify to maintain class distribution
)

print(f"Shape of X_train_diverse: {X_train_diverse.shape}")
print(f"Shape of X_test_diverse: {X_test_diverse.shape}")
print(f"Distribution of categories in y_train_diverse:\n{y_train_diverse.value_counts()}")
print(f"Distribution of categories in y_test_diverse:\n{y_test_diverse.value_counts()}")

"""### TF-IDF Vectorization for Diverse Data

We will re-initialize `TfidfVectorizer` and apply it to our diverse training and testing sets. This step converts the text data into numerical features that the machine learning model can process.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Create a new TF-IDF vectorizer for the diverse dataset
tfidf_diverse = TfidfVectorizer()

# Fit and transform the training data, then transform the test data
X_train_diverse_vec = tfidf_diverse.fit_transform(X_train_diverse)
X_test_diverse_vec = tfidf_diverse.transform(X_test_diverse)

print(f"Shape of vectorized X_train_diverse: {X_train_diverse_vec.shape}")
print(f"Shape of vectorized X_test_diverse: {X_test_diverse_vec.shape}")

"""### Model Training and Evaluation on Diverse Data

Now, we'll train a `MultinomialNB` model on the vectorized diverse training data and evaluate its performance on the diverse test set. We expect to see a more realistic accuracy score now that the dataset contains multiple categories.
"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the Multinomial Naive Bayes model on the diverse data
model_diverse = MultinomialNB()
model_diverse.fit(X_train_diverse_vec, y_train_diverse)

# Make predictions on the diverse test set
y_pred_diverse = model_diverse.predict(X_test_diverse_vec)

# Evaluate the model's performance
print("Accuracy on diverse dataset:", accuracy_score(y_test_diverse, y_pred_diverse))
print("\nClassification Report on diverse dataset:\n", classification_report(y_test_diverse, y_pred_diverse))

TfidfVectorizer(max_features=5000)  # increasing the feature as accuracy is 0.1

df['Category'].value_counts()

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_diverse_vec, y_train_diverse)

from sklearn.metrics import accuracy_score

y_train_pred = model.predict(X_train_diverse_vec)
train_accuracy = accuracy_score(y_train_diverse, y_train_pred)

print("Training Accuracy:", train_accuracy)

y_test_pred = model.predict(X_test_diverse_vec)

test_accuracy = accuracy_score(y_test_diverse, y_test_pred)

print("Testing Accuracy:", test_accuracy)

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# split FIRST
X_train, X_test, y_train, y_test = train_test_split(
    df['clean_resume'], df['Category'], test_size=0.2, random_state=42
)

# fit ONLY on training
tfidf = TfidfVectorizer(max_features=5000)
X_train = tfidf.fit_transform(X_train)
X_test = tfidf.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_diverse_vec, y_train_diverse)

model = LogisticRegression(max_iter=1000, C=0.5)

TfidfVectorizer(max_features=3000, stop_words='english')

df['Category'].value_counts()

model.fit(X_train_diverse_vec, y_train_diverse)
print("Train:", model.score(X_train_diverse_vec, y_train_diverse))
print("Test:", model.score(X_test_diverse_vec, y_test_diverse))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['clean_resume'], df['Category'], test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)
X_train = tfidf.fit_transform(X_train)   # fit ONLY on train
X_test = tfidf.transform(X_test)         # transform test

df['clean_resume'].duplicated().sum()

df = df.drop_duplicates(subset='clean_resume')

df['Category'].value_counts()

import pandas as pd

results = pd.DataFrame({
    'Actual': y_test_diverse,
    'Predicted': model.predict(X_test_diverse_vec)
})

print(results.head(20))

from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test_diverse, model.predict(X_test_diverse_vec)))

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000, class_weight='balanced')
model.fit(X_train_diverse_vec, y_train_diverse)

print("Train:", model.score(X_train_diverse_vec, y_train_diverse))
print("Test:", model.score(X_test_diverse_vec, y_test_diverse))

# how many exact duplicate texts?
print("Duplicates:", df['clean_resume'].duplicated().sum())

train_set = set(X_train_diverse)   # use raw text BEFORE TF-IDF
test_set  = set(X_test_diverse)

overlap = train_set.intersection(test_set)
print("Overlap count:", len(overlap))

import pandas as pd

preds = model.predict(X_test_diverse_vec)
print(pd.Series(preds).value_counts())

print(df['Category'].value_counts(normalize=True))

model = LogisticRegression(max_iter=2000, class_weight='balanced')

print(df['clean_resume'].head(5))

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# split using the diverse dataset
X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    df_diverse['clean_resume'], df_diverse['Category'], test_size=0.5, random_state=42, stratify=df_diverse['Category']
)

# tfidf
tfidf = TfidfVectorizer(max_features=4000, stop_words='english')
X_train = tfidf.fit_transform(X_train_raw)
X_test = tfidf.transform(X_test_raw)

# model
model = LogisticRegression(max_iter=2000, class_weight='balanced')
model.fit(X_train, y_train)

print("Train:", model.score(X_train, y_train))
print("Test:", model.score(X_test, y_test))

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000, C=0.3)
model.fit(X_train, y_train)

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english',
    ngram_range=(1,2)   # <-- important
)

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(X_train, y_train)

model = LogisticRegression(max_iter=2000, class_weight='balanced')
model.fit(X_train, y_train)

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english',
    ngram_range=(1,2)
)

X_train = tfidf.fit_transform(X_train_raw)
X_test = tfidf.transform(X_test_raw)

from sklearn.svm import LinearSVC
model = LinearSVC()

model.fit(X_train, y_train)

print("Train:", model.score(X_train, y_train))
print("Test:", model.score(X_test, y_test))

def clean_text(text):
  return text

def predict_resume(text):
    if not text.strip():
        return "Invalid input", "N/A"
    vector = tfidf.transform([text])
    pred = model.predict(vector)[0]

    if hasattr(model, "predict_proba"):
        prob = model.predict_proba(vector).max()
        return pred, prob
    else:
        return pred, "N/A"

from sklearn.model_selection import GridSearchCV, KFold
from sklearn.linear_model import LogisticRegression

params = {
    'C': [0.1, 0.3, 1, 3],
}

# Use KFold instead of default StratifiedKFold to avoid ValueError with small, sparse classes
# Note: With only 1 sample per class in y_train, cross-validation results might not be robust.
grid = GridSearchCV(LogisticRegression(max_iter=2000), params, cv=KFold(n_splits=2))
grid.fit(X_train, y_train)

print("Best:", grid.best_params_)

tfidf = TfidfVectorizer(
    max_features=7000,
    stop_words='english',
    ngram_range=(1,2)
)

X_train = tfidf.fit_transform(X_train_raw)
X_test = tfidf.transform(X_test_raw)

from sklearn.model_selection import cross_val_score, KFold

scores = cross_val_score(model, X_train, y_train, cv=KFold(n_splits=3)) # Use KFold to avoid stratification issues with small classes
print(scores.mean())

def get_confidence(text):
    vector = tfidf.transform([text])
    return model.predict_proba(vector).max()

def keyword_match(text):
    keywords = ["python", "machine learning", "data"]
    return [k for k in keywords if k in text.lower()]

def extract_skills(text):
    skills = ["python", "machine learning", "sql", "excel"]
    return [s for s in skills if s in text.lower()]

def handle_prediction_result(result):
    if result["confidence"] and result["confidence"] < 0.5:
        return {"category": "Uncertain", "confidence": result["confidence"]}
    return result # Return the original result if not uncertain

user_input = "This is a sample resume text for prediction."
tfidf.fit(X_train_raw) # Fit the tfidf vectorizer on training data
features = tfidf.transform([user_input])

tfidf.fit(df['clean_resume'])   # training step

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Use the already prepared and vectorized diverse data:
# X_train_diverse_vec, y_train_diverse, X_test_diverse_vec, y_test_diverse
# and tfidf_diverse are available from previous cells.

model = LinearSVC()
model.fit(X_train_diverse_vec, y_train_diverse)

# Evaluate the model's performance on the diverse test set
y_pred_diverse = model.predict(X_test_diverse_vec)
print("Accuracy on diverse dataset (LinearSVC):", accuracy_score(y_test_diverse, y_pred_diverse))
print("\nClassification Report on diverse dataset (LinearSVC):\n", classification_report(y_test_diverse, y_pred_diverse))

# Save the trained model and the tfidf vectorizer that was used for the diverse data
joblib.dump(model, 'model.pkl')
joblib.dump(tfidf_diverse, 'tfidf.pkl') # Use tfidf_diverse, which was fitted on the diverse data

import joblib

model = joblib.load("model.pkl")
tfidf = joblib.load("tfidf.pkl")